[envs.deps]
python = "3.9"
dependencies = ["pip-tools"]
skip-install = true

[envs.deps.scripts]
update-env = [
    "python --version",
    "pip-compile --resolver=backtracking --generate-hashes --upgrade requirements-env.in --output-file requirements-env.txt",
]
update-libs = [
    "python --version",
    "pip-compile --resolver=backtracking --generate-hashes --upgrade requirements-libs.in --output-file requirements-libs.txt",
]
