[tool.esbonio.sphinx]
# buildCommand = ["sphinx-build", "-M", "dirhtml", ".", "./_build"]
pythonCommand = ["hatch", "-e", "docs", "run", "python"]

[tool.hatch.envs.docs]
installer = 'uv'
skip-install = true
dependencies = [
    "aiosqlite",
    "sphinx",
    "sphinx-design",
    "furo",
    "myst-parser",
    "platformdirs",
    "pytest_lsp>=1.0b0",
    "pygls>=2.0a0",
]

[tool.hatch.envs.docs.env-vars]
UV_PRERELEASE = "allow"

[tool.hatch.envs.docs.scripts]
build = "sphinx-build -M dirhtml . ./_build"
