name: Documentation
on:
  pull_request:
    branches:
    - release
    - develop
    paths:
    - 'docs/**'
    - 'lib/esbonio/**'
    - 'lib/esbonio-extensions/**'
  push:
    branches:
    - release
    - develop
    paths:
    - 'docs/**'
    - 'lib/esbonio/**'
    - 'lib/esbonio-extensions/**'

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - run: |
        set -e

        python --version
        python -m pip install --upgrade pip
        python -m pip install -r docs/requirements.txt

      name: Setup Environment

    - id: build
      run: |
        set -e

        cd docs
        make html
      name: Build Docs

    - name: 'Upload Aritfact'
      uses: actions/upload-artifact@v3
      with:
        name: 'docs'
        path: 'docs/_build/${{ steps.build.outputs.version }}'

    - name: 'Publish Docs'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: docs/_build/${{ steps.build.outputs.version }}
        target-folder: docs/${{ steps.build.outputs.version }}
        clean: true
      if: success() && ( startsWith(github.ref, 'refs/heads/release') || startsWith(github.ref, 'refs/heads/develop') )
