name: 'PR: esbonio'
on:
  pull_request:
    branches:
    - develop
    - release
    paths:
    - 'lib/esbonio/**'
    - '!lib/esbonio/changes/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Setup Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
      with:
        python-version: "3.11"

    - run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install --upgrade hatch towncrier
      name: Setup Environment

    - run: |
        set -e
        ./scripts/make_release.py lsp
      name: Set Version

    - uses: hynek/build-and-inspect-python-package@2abe76da66d0a6a4a227101f9348ee855797cfa5  # v3.0.1
      id: baipp
      with:
        path: lib/esbonio

    outputs:
      python-versions: ${{ steps.baipp.outputs.supported_python_classifiers_json_array }}

  test:
    needs: build
    name: "Python v${{ matrix.python-version }} -- ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(needs.build.outputs.python-versions) }}
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - run: |
        python --version
        python -m pip install --upgrade hatch
      name: Setup Environment

    - run: |
        cd lib/esbonio

        hatch test -c -i py=${{ matrix.python-version }}
      name: Run Tests
