name: 'Release'
on:
  push:
    branches:
    - release
    paths:
    - 'code/**'
    - 'lib/esbonio/**'

permissions: {}

jobs:
  trigger:
    runs-on: ubuntu-latest
    outputs:
      lsp: ${{steps.check-lsp.outputs.build}}
      code: ${{steps.check-code.outputs.build}}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
        fetch-depth: 0

    - run: |
        if [ -z "${BASE_REF}" ]; then
          echo "BASE=HEAD^" >> $GITHUB_ENV
        else
          echo "BASE=origin/${BASE_REF}" >> $GITHUB_ENV
        fi
      name: Determine base
      env:
        BASE_REF: ${{ github.base_ref }}

    - id: check-code
      run: |
        set -e
        echo ${BASE}

        ./scripts/should-build.sh vscode
      name: "Build VSCode?"

    - id: check-lsp
      run: |
        set -e
        echo ${BASE}

        ./scripts/should-build.sh lsp
      name: "Build LSP?"

  lsp-release:
    needs: trigger
    if: needs.trigger.outputs.lsp
    name: esbonio release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.info.outputs.version }}
    environment:
      name: pypi
      url: https://pypi.org/p/esbonio
    permissions:
      contents: write
      id-token: write

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: true  # needed to push commits to the release branch

    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
        python-version: "3.10"

    - run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install --upgrade hatch towncrier docutils
      name: Setup Environment

    - run: |
        set -e

        ./scripts/make_release.py lsp
      name: Set Version
      id: info

    - name: Package
      run: |
        cd lib/esbonio
        hatch build

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: 'dist'
        path: lib/esbonio/dist

    - name: Publish
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b  # v1.14.0
      with:
        packages-dir: lib/esbonio/dist/

    - name: Create Release
      run: |
        gh release create "${RELEASE_TAG}" \
          --title "Esbonio Language Server v${VERSION} - ${RELEASE_DATE}" \
          -F lib/esbonio/.changes.html \
          ./lib/esbonio/dist/*
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  build-vsix:
    needs: [trigger, lsp-release]
    if: |
      always() &&
      needs.trigger.outputs.code &&
      (needs.lsp-release.result == 'success' || needs.lsp-release.result == 'skipped')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: true  # needed to push commits to the release branch

    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
      with:
        package-manager-cache: false

    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
        # This must be the minimum Python version we support
        python-version: "3.10"

    - run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install --upgrade hatch towncrier docutils
      name: Install Build Tools

    - run: |
        set -e
        ./scripts/make_release.py vscode
      name: Set Version

    - run: |
        set -e
        cd code
        echo "ESBONIO_WHL='${ESBONIO_WHL}'"
        make dist
      name: Package Extension
      env:
        # Use version of esbonio on PyPi for release builds
        ESBONIO_WHL: "${{ case(needs.lsp-release.outputs.version != '', format('esbonio=={0}', needs.lsp-release.outputs.version), 'esbonio') }}"

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: 'vsix'
        path: code/*.vsix
        if-no-files-found: error

    - name: Create Release
      run: |
        gh release create "${RELEASE_TAG}" \
          --title "Esbonio VSCode Extension v${VERSION} - ${RELEASE_DATE}" \
          -F code/.changes.html \
          ./code/*.vsix
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  marketplace-release:
    name: vscode release
    needs: build-vsix
    if: always() && needs.build-vsix.result == 'success'
    runs-on: ubuntu-latest
    environment:
      name: vscode-marketplace
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        persist-credentials: false

    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
      with:
        package-manager-cache: false

    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
      name: 'Download Extension'
      with:
        name: 'vsix'
        path: code

    - name: 'Publish Extension'
      run: |
        cd code
        npm ci --prefer-offline
        npm run deploy-vsce
      env:
        VSCE_PAT: ${{ secrets.VSCODE_PAT }}

  open-vsx-release:
    name: open vsx release
    needs: build-vsix
    if: always() && needs.build-vsix.result == 'success'
    runs-on: ubuntu-latest
    environment:
      name: open-vsx
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
      with:
        package-manager-cache: false

    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8.0.1
      name: 'Download Extension'
      with:
        name: 'vsix'
        path: code

    - name: 'Publish Extension'
      run: |
        cd code
        npm ci --prefer-offline
        npm run deploy-ovsx
      env:
        OVSX_PAT: ${{ secrets.OVSX_PAT }}
