name: 'PR: esbonio'
on:
  pull_request:
    branches:
    - develop
    - release
    paths:
    - 'lib/esbonio/**'
    - '!lib/esbonio/changes/**'

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Setup Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
      with:
        python-version: "3.11"

    - run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install --upgrade hatch towncrier
      name: Setup Environment

    - run: |
        set -e
        ./scripts/make_release.py lsp
      name: Set Version

    # TODO: https://github.com/hynek/build-and-inspect-python-package/tree/main#define-python-version-matrix-based-on-package-metadata
    - uses: hynek/build-and-inspect-python-package@d44ca7d91762de7a7d5436ddae667c6da6d1c3df # v 2.18.0
      with:
        path: lib/esbonio

  test:
    name: "Python v${{ matrix.python-version }} -- ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - run: |
        python --version
        python -m pip install --upgrade hatch
      name: Setup Environment

    - run: |
        cd lib/esbonio

        hatch test -c -i py=${{ matrix.python-version }}
      name: Run Tests
