name: 'PR: vscode'
on:
  pull_request:
    branches:
    - develop
    - release
    paths:
    - 'code/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
      with:
        package-manager-cache: false

    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
      with:
        # This must be the minimum Python version we support
        python-version: "3.10"

    - run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install --upgrade hatch towncrier
      name: Install Build Tools

    - run: |
        set -e
        ./scripts/make_release.py lsp
        ./scripts/make_release.py vscode
      name: Set Versions

    - run: |
        set -e
        cd lib/esbonio
        hatch build
        echo "ESBONIO_WHL=$(find $(pwd)/dist -name '*.whl')" >> $GITHUB_ENV
      name: Package Language Server

    - run: |
        set -e
        cd code

        # Use in-repo version of esbonio for dev builds
        echo "whl=${ESBONIO_WHL}"
        ESBONIO=${ESBONIO_WHL} make dist
      id: assets
      name: Package Extension

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: 'vsix'
        path: code/*.vsix
        if-no-files-found: error
        retention-days: 7

  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/swyddfa/esbonio-devenv

    timeout-minutes: 20
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - run: |
        cd code
        make test
      name: Run Tests
