name: 'PR: vscode'
on:
  pull_request:
    branches:
    - develop
    - release
    paths:
    - 'code/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v6'

    - uses: 'actions/setup-node@v6'
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: 'code/package-lock.json'

    - uses: 'actions/setup-python@v6'
      with:
        # This must be the minimum Python version we support
        python-version: "3.10"

    - name: Pip cache
      uses: actions/cache@v5
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-vscode-pip-deps-${{ hashFiles('code/requirements-*.txt') }}
        restore-keys: |
          ${{ runner.os }}-vscode-pip-deps

    - run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install --upgrade hatch towncrier
      name: Install Build Tools

    - run: |
        set -e
        ./scripts/make_release.py lsp
        ./scripts/make_release.py vscode
      name: Set Versions

    - run: |
        set -e
        cd lib/esbonio
        hatch build
        echo "ESBONIO_WHL=$(find $(pwd)/dist -name '*.whl')" >> $GITHUB_ENV
      name: Package Language Server

    - run: |
        set -e
        cd code

        # Use in-repo version of esbonio for dev builds
        echo "whl=${ESBONIO_WHL}"
        ESBONIO=${ESBONIO_WHL} make dist
      id: assets
      name: Package Extension

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v7
      with:
        name: 'vsix'
        path: code/*.vsix
        if-no-files-found: error
        retention-days: 7

  test:
    name: "Python v${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    # container:
    #   image: ghcr.io/swyddfa/esbonio-devenv
    #   credentials:
    #      username: ${{ github.actor }}
    #      password: ${{ secrets.github_token }}

    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v6

    - uses: 'actions/setup-node@v6'
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: 'code/package-lock.json'

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - run: |
        cd code
        make dev-deps
        npx tsc -p .

        # Force the extension to use this version of Python
        python --version
        export ESBONIO_SERVER_PYCMD=$(command -v python)
        echo $ESBONIO_SERVER_PYCMD

        xvfb-run -a npm run test
      name: Run Tests
