name: 'PR: vscode'
on:
  pull_request:
    branches:
    - develop
    - release
    paths:
    - 'code/**'

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
      with:
        package-manager-cache: false

    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
      with:
        # This must be the minimum Python version we support
        python-version: "3.10"

    - run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install --upgrade hatch towncrier
      name: Install Build Tools

    - run: |
        set -e
        ./scripts/make_release.py lsp
        ./scripts/make_release.py vscode
      name: Set Versions

    - run: |
        set -e
        cd lib/esbonio
        hatch build
        echo "ESBONIO_WHL=$(find $(pwd)/dist -name '*.whl')" >> $GITHUB_ENV
      name: Package Language Server

    - run: |
        set -e
        cd code

        # Use in-repo version of esbonio for dev builds
        echo "whl=${ESBONIO_WHL}"
        ESBONIO=${ESBONIO_WHL} make dist
      id: assets
      name: Package Extension

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
      with:
        name: 'vsix'
        path: code/*.vsix
        if-no-files-found: error
        retention-days: 7

  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/swyddfa/esbonio-devenv

    timeout-minutes: 20
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - run: |
        cd code
        make test
      name: Run Tests
