name: 'Release: vscode-extension'
on:
  push:
    branches:
    - release
    paths:
    - 'code/**'

jobs:
  vscode:
    name: 'vscode extension release'
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v4'

    - uses: 'actions/setup-node@v3'
      with:
        node-version: 16.x

    - uses: 'actions/setup-python@v4'
      with:
        python-version: "3.10"

    - run: |
        sudo apt update
        sudo apt install pandoc

        python --version
        python -m pip install --upgrade pip
        python -m pip install --upgrade tox bump2version towncrier docutils
      name: Install Build Tools

    - run: |
        set -e

        ./scripts/make-release.sh vscode
      name: Set Version
      id: info

    - run: |
        cd code
        npm ci
        npm run package
      name: Package Extension

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: 'vsix'
        path: code/*.vsix

    - name: 'Publish Extension'
      run: |
        cd code
        npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCODE_PAT }}

    - name: Create Release
      run: |
        gh release create "${RELEASE_TAG}" \
          --title "Esbonio VSCode Extension v${VERSION} - ${RELEASE_DATE}" \
          -F code/.changes.html \
          ./code/*.vsix
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
